### ISSUE TITLE
SOCK_DGRAM instead of SOCK_RAW

### ISSUE THREAD

**Issue by majek** [zaphar/icmp-socket#3]
Hi,

you are using SOCK_RAW
```
socket(AF_INET, SOCK_RAW|SOCK_CLOEXEC, IPPROTO_ICMP) = -1 EPERM (Operation not permitted)
```

Which requires permissions.
Have you considered using SOCK_DGRAM which does not require permissions as long as `net.ipv4.ping_group_range` is set right?

**Comment by zaphar** [comment]
It is not something I've needed yet but I'm not opposed to it as an option. I would want it to be optional instead of required I think though.

**Comment by zaphar** [comment]
@majek, Would the above pull request fit your use case?
